version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - app
    volumes:
      - ./backend:/work/backend

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./backend:/work/backend
      - ./.env:/work/backend/.env
      - laravel-vendor-volume:/work/backend/vendor
    depends_on:
      - db
      - redis

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql-volume:/var/lib/mysql

  redis:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    ports:
      - 6379:6379
    volumes:
      - redis-volume:/data

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - 8081:8080
      - 8083:8083
    volumes:
      - .:/work
      - node-modules-volume:/work/node_modules
    tty: true

volumes:
  mysql-volume:
  laravel-vendor-volume:
  node-modules-volume:
  redis-volume:
